### ISSUE TITLE
Curved Progress Bar displays Squarish Progress when progress is less than 2%

### ISSUE THREAD

**Issue by HirogaKatageri** [skydoves/ProgressView#1]
**Please complete the following information:**
- Library Version: 1.0.1
- Affected Device(s): Any
 
**Describe the Bug:**

When the progress bar has a very strong radius or is very curved. The progress bar is showing a more squarish progress than a curved one.

**Expected Behavior:**

Should still show a more curved one.

![Screenshot_20190829-155653](https://user-images.githubusercontent.com/8166484/63921854-2360aa00-ca76-11e9-85f5-9af7b973612d.png)

**Comment by skydoves** [comment]
Released a new version [1.0.3](https://github.com/skydoves/ProgressView/releases/tag/1.0.3).
@anoop44 Thank you for your contributions :)
