### ISSUE TITLE
border color

### ISSUE THREAD

**Issue by PaolinoAngeletti** [skydoves/ProgressView#12]
i need to change the border color, because i want to se backgroud as trasparent

**Comment by PaolinoAngeletti** [comment]
solved with this code:

`private fun updateBackground() {
    this.background = GradientDrawable().apply {
      cornerRadius = radius
      setColor(colorBackground)
      setStroke(3, Color.WHITE)
    }
  }`



of course, i haven't used attribute set , you can complete the update with this params

**Comment by skydoves** [comment]
Hi @PaolinoAngeletti !
It will be included in the next release.
Thanks for your issue :)

**Comment by skydoves** [comment]
Hi, a new version [1.0.9](https://github.com/skydoves/ProgressView/releases/tag/1.0.9) is released!
