### ISSUE TITLE
center the text into progress

### ISSUE THREAD

**Issue by PaolinoAngeletti** [skydoves/ProgressView#13]
it would be usefull to center the text instead of put it where there is space

**Comment by PaolinoAngeletti** [comment]
`private fun setLabelViewPosition(position: Float)
  {
    if (isVertical()) {
      labelView.y = position
    } else {
      labelView.x = (getViewSize(this) / 2f) - (this.labelView.width / 2f)
    }
  }`

solved with this line code

**Comment by skydoves** [comment]
Hi @PaolinoAngeletti 
I will include this issue in the next release.
Thank you for your issue :)

**Comment by skydoves** [comment]
Hi, a new version [1.0.9](https://github.com/skydoves/ProgressView/releases/tag/1.0.9) is released!
