### ISSUE TITLE
ProgressView is used in RecyclerView

### ISSUE THREAD

**Issue by sceneren** [skydoves/ProgressView#14]
**Please complete the following information:**
- Library Version 1.0.9
- Affected Device(s) ALL
 
**Describe the Bug:**
ProgressView can't set progress, but in the  getProgress() has value

**Comment by skydoves** [comment]
As you can see this [demo codes](https://github.com/skydoves/ProgressView/blob/master/app/src/main/java/com/skydoves/progressviewdemo/MainActivity.kt#L58), you can set `progress` programmatically.
