### ISSUE TITLE
RTL please

### ISSUE THREAD

**Issue by rizkirakasiwi** [skydoves/ProgressView#19]
progressview support RTL but the label inside the progress not going RTL, i hope you can add this feature

**Comment by rizkirakasiwi** [comment]
you can use

**Comment by rizkirakasiwi** [comment]
owh, i do this
`progressviewl.labelView.layoutDirection = View.LAYOUT_DIRECTION_RTL`

**Comment by skydoves** [comment]
Hi @rizkirakasiwi,
It's a great point! I will consider supporting `supportRTL` method that handles RTL both the progressView and the label !

**Comment by rizkirakasiwi** [comment]
when i use RTL mode, i can't use `app:progressView_labelConstraints="align_progress"` because the label animation is still from left to right, but everything works perfectly if I use `app:progressView_labelConstraints="align_constraint"`
