### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by manumathew17** [skydoves/ProgressView#24]
Getting error after adding this dependency
D:\android\handheld\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:6541: error: resource android:attr/lStar not found.
error: failed linking references.

**Comment by skydoves** [comment]
Hi @manumathew17,
Regarding the crash, `android:attr/lStar` is not related to this library.
Please try to build after clean the project.

**Comment by manumathew17** [comment]
Hi @skydoves 
The issue got resolved once project upgrade the min sdk to 32 
Thanks
