### ISSUE TITLE
[Feature Req] Animating Progress From Previous Progress

### ISSUE THREAD

**Issue by tanurwijaya** [skydoves/ProgressView#4]
Hi, I love your library.

Currently, I'm implementing multipage registration with viewpager and using your library to show the current progress.

But, I found if it will more 'nice to see?' if the animation start from previous progress.

```java
fun progressAnimate() { ... }
// instead of reset the value to 0, why not using the old progress value
```

**Comment by skydoves** [comment]
@tanurwijaya 
Hi, sorry for the late reply!
Here is a new version [1.0.6](https://github.com/skydoves/ProgressView/releases), you can use the new attribute `progressView_progressFromPrevious`. The default value is `false`.
Thank you for your issue :)

**Comment by tanurwijaya** [comment]
Thanks @skydoves , looks good to me, love your lib.
