### ISSUE TITLE
Cant find OnProgressClickListener written in Java

### ISSUE THREAD

**Issue by Dor-Sloim** [skydoves/ProgressView#5]
Hi, is there an OnProgressClickListener written in Java ?(not the kotlin one)
If not, do you think you can add one so we will be able to do this:

`  
progressView.setOnProgressClickListener(new OnProgressClickListener()
        {

            @Override
            public void onClickProgress(boolean b)
            {
                Toast.makeText(MainActivity.this, progressView.getProgress() + "% selected: " + b, Toast.LENGTH_SHORT).show();
            }
        })
`

**(Im coding in Java)**
so im getting the error:

> class file for kotlin.jvm.functions.Function1 not found

Thanks a lot.

**Comment by skydoves** [comment]
@Dor-Sloim 
Hi, it seems not has any problem setting `onClickProgress` a listener in Java like this.
```java
progressView.setOnProgressClickListener(new OnProgressClickListener() {
      @Override
      public void onClickProgress(boolean b) {

      }
 });
```

**Comment by Dor-Sloim** [comment]
Thanks for answering.
I copied your code but still getting the same error:

>  error: cannot access Function1
> class file for kotlin.jvm.functions.Function1 not found

Do i have to enable kotlin support for the project for this to work?

**Comment by skydoves** [comment]
@Dor-Sloim 
Hi, it is released a new version [1.0.5](https://github.com/skydoves/ProgressView/releases/tag/1.0.5) now.
Thank you for your issue!

**Comment by Dor-Sloim** [comment]
Updated to 1.0.5 but **still got the same error**.

**Comment by Dor-Sloim** [comment]
Also, i'm getting the same error when using `setOnProgressChangeListener`.
The error:

> error: cannot access Function1

> class file for kotlin.jvm.functions.Function1 not found


The only working listener for me is the `setOnClickListener(new View.OnClickListener()`.

Do you think you can add java support?
I really love this library.

**Comment by Dor-Sloim** [comment]
I got this to work by configuring Kotlin for project unfortunately
